image: node

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy staging
  - deploy production
  - production tests

build site:
  stage: build
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - CI=false
    - npm i
    - npm i -g create-react-app
    - yarn run build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
  artifacts:
    paths:
      - ./public


test artifact:
  image: alpine
  stage: test
  script:
    - grep -q "calculator" ./public/index.html

test website:
  stage: test
  script:
    - npm i
    - npm i -g create-react-app
    - yarn run start
    - sleep 20 &
    - curl -m 5 "http://localhost:3000" | tac | tac | grep -q "calculator"

deploy staging:
  stage: deploy staging
  environment:
    name: staging
    url: http://cb591-loan-amortization-staging.surge.sh
  script:
    - npm i -g surge
    - surge --project ./public --domain http://cb591-loan-amortization-staging.surge.sh

deploy production:
  stage: deploy production
  environment:
    name: staging
    url: http://cb591-loan-amortization.surge.sh
  script:
    - npm i -g surge
    - surge --project ./public --domain http://cb591-loan-amortization.surge.sh

production tests:
  image: alpine
  stage: production tests
  script:
    - apk add --no-cache curl
    - curl -s "http://cb591-loan-amortization.surge.sh" | grep -q "calculator"
    - curl -s "http://defiant-goat.surge.sh" | grep -q "$CI_COMMIT_SHORT_SHA"