image: node

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

variables:
  STAGING_DOMAIN: http://cb591-loan-amortization-staging.surge.sh
  PRODUCTION_DOMAIN: http://cb591-loan-amortization.surge.sh

stages:
  - build
  - test
  - deploy staging
  - deploy production
  - production tests

build site:
  stage: build
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - CI=false
    - npm i
    - npm i -g create-react-app
    - yarn run build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
  artifacts:
    paths:
      - ./public


test artifact:
  image: alpine
  stage: test
  script:
    - grep -q "calculator" ./public/index.html

test website:
  stage: test
  script:
    - npm i
    - npm i -g create-react-app
    - yarn run start &
    - sleep 3
    - curl "http://localhost:3000" | tac | tac | grep -q "calculator"

deploy staging:
  stage: deploy staging
  environment:
    name: staging
    url: $STAGING_DOMAIN
  script:
    - npm i -g surge
    - surge --project ./public --domain $STAGING_DOMAIN

deploy production:
  stage: deploy production
  environment:
    name: production
    url: $PRODUCTION_DOMAIN
  when: manual
  script:
    - npm i -g surge
    - surge --project ./public --domain $PRODUCTION_DOMAIN

production tests:
  image: alpine
  stage: production tests
  script:
    - apk add --no-cache curl
    - curl -s "$PRODUCTION_DOMAIN" | grep -q "calculator"
    - curl -s "$PRODUCTION_DOMAIN" | grep -q "$CI_COMMIT_SHORT_SHA"