image: node

stages:
  - build
  - test
  - deploy
  - post-deploy

build site:
  stage: build
  script:
    - npm i
    - npm i -g create-react-app
    - yarn run build
  artifacts:
    paths:
      - ./public


test artifact:
  image: alpine
  stage: test
  script:
    - grep -q "Calculator" ./public/index.html

test website:
  stage: test
  script:
    - npm i
    - npm i -g create-react-app
    - yarn run start
    - sleep 3
    - curl "http://localhost:3000" | tac | grep -q "Calculator"

deploy to surge:
  stage: deploy
  script:
    - npm i -g surge
    - surge --project ./public --domain http://cb591-loan-amortization.surge.sh

test deployment:
  image: alpine
  stage: post-deploy
  script:
    - apk add --no-cache curl
    - curl -s "http://cb591-loan-amortization.surge.sh" | grep -q "Calculator"
    - curl -s "http://cb591-loan-amortization.surge.sh" | grep -q "$CI_COMMIT_SHORT_SHA"
